version: "3.8"
   
services:
    server:
        container_name: server
        build:
          context: ./server
        command: gunicorn core.wsgi --bind 0.0.0.0:8000 
        volumes:
            - ./server:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=amqp://rabbitmq
        depends_on:
            - db
            - redis
            - rabbitmq
    worker-one:
        container_name: worker-one
        restart: always
        build:
          context: ./server
        command: python manage.py celery
        volumes:
            - ./server:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=amqp://rabbitmq
        depends_on:
            - server
            - db
            - rabbitmq
            - redis
    worker-two:
        container_name: worker-two
        restart: always
        build:
          context: ./server
        command: python manage.py celery
        volumes:
            - ./server:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=amqp://rabbitmq
        depends_on:
            - server
            - db
            - rabbitmq
            - redis
    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./pgdata/db:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
    rabbitmq:
      container_name: rabbitmq
      restart: always
      image: rabbitmq:3.10-alpine
      volumes:
        - ./rabbitmq_data:/var/lib/rabbitmq
    server-migrations:
      build:
        context: ./server
      command: python manage.py migrate
      volumes:
          - ./server:/usr/src/app
      depends_on:
        - db
        
volumes:
    pgdata:
    rabbitmq_data:
